### ISSUE TITLE
Unable to log in via TTN Console and select device

### ISSUE THREAD

**Issue by proffalken** [ttnmapper/ttnmapper-android-v3#1]
On previous versions of the app, I was able to log in to my account and select a device.

This doesn't appear to be a possibility anymore - the button is there, but it is greyed out.

Given the complexity of having to type in the devid/appid/appkey, it would be great to have this functionality back!

**Comment by jpmeijers** [comment]
This will be added again. Greyed out settings are features that are planned but still need to be added or completed.

In the meantime I have added the deep linking ability back into the app, so you are able to use the "Use with TTN Mapper" button under a specific device in the TTN Mobile app to configure your keys in the TTN Mapper app.

See:
https://play.google.com/store/apps/details?id=com.async.ttn

**Comment by jpmeijers** [comment]
The feature was added and the update should be coming out on the Play store within minutes.
