### ISSUE TITLE
Zoom levels of app are coarse

### ISSUE THREAD

**Issue by pe1mew** [ttnmapper/ttnmapper-android-v3#11]
The zoom levels of the v3 app are coarse. At various zoom levels the place names are very pixalized. This results in very unclear maps.
Changing the moment of zoom to a higher resolution will result in a better user experience.

**Comment by jpmeijers** [comment]
The open source mapping library we currently use doesn't have a nice way of handling this. We basically have two option. Either the current one with text that is blurry and a good readable size, or text that is sharp but very small. See the two screenshots as explanation. My feeling currently goes towards the smaller sharp text, as labels aren't that important while mapping.

![Screenshot_20190309-153809_TTN Mapper](https://user-images.githubusercontent.com/948278/54072491-1790e980-4284-11e9-8167-cd506ddf59b3.jpg)
![Screenshot_20190309-153835](https://user-images.githubusercontent.com/948278/54072493-1b247080-4284-11e9-9993-87736307d867.png)

**Comment by pe1mew** [comment]
I agree with the motivation for detailed maps and small text.
The test is satisfying.
