### ISSUE TITLE
starting and moving, but no packages received

### ISSUE THREAD

**Issue by itsbrody** [ttnmapper/ttnmapper-android-v3#23]
Since beginning of the year I take care around and use Things network. Some days ago I found ttnmapper.org and find this interesting. Discovered there that a mobile app is available and installed it yesterday. Configured it with the there mentioned lab (I think successfully).

While starting first inhouse I got errors about the GPX fix, but when reaching my car (at the company, where we have a ttn gateway!), that problem has gone, when mapping is running. Now I'd suggest to receive packages from any near gateway, but this does not working and not only our company provides an active ttn gateway, also other locations do so.
Any idea?

**Comment by jpmeijers** [comment]
This does not sound like a bug in the app, but rather a usage or configuration issue. Rather try asking for support on #ttn-mapper on the TTN Slack.

**Comment by itsbrody** [comment]
> 
> 
> This does not sound like a bug in the app, but rather a usage or configuration issue. Rather try asking for support on #ttn-mapper on the TTN Slack.

I'm not able to do more than configuring the app along what the app provides. Just did it ... if this is your only help, I only can forget your app and remove it. Good luck with such type of support...

**Comment by jpmeijers** [comment]
> Good luck with such type of support...

What kind of support do you expect from a free service?

All I'm saying is use the appropriate channels for support, and leave the bug reporting channels for their purpose.

**Comment by itsbrody** [comment]
sorry, that I offered to use my phone for providing data for a free service using your app, which shows a problem. Won't happen again...
