### ISSUE TITLE
Release APK or via Fdroid store?

### ISSUE THREAD

**Issue by Matthias84** [ttnmapper/ttnmapper-android-v3#32]
Hi, combining my OpenStreetMap hobby with IoT , the TTNMapper sounds like a logical consequence to continue my work ;-)

Unfortunatly if you use LineageOS or any other Android AOSP based fork, you will be unable to make use of the Google Playstore to get the binary.
Thats why I would like to encourage also the non so mainstream users to contribute measurements via custom rom OSes. Usually Fdroid asks you to follow some design [policies and to setup CI templates](https://f-droid.org/de/docs/Inclusion_Policy). Maybe it's a good first start to share the APK, so we can see how far we can get using Google fake services by [microg](https://microg.org/)?

**Comment by jpmeijers** [comment]
Closing due to duplicate of #7

**Comment by Matthias84** [comment]
Sorry for creating dublicate. I browsed the short list, but obviously was focused on fdroid int title :confused:
