### ISSUE TITLE
Map theme is missing roads

### ISSUE THREAD

**Issue by ryanteck** [ttnmapper/ttnmapper-android-v3#4]
Just wondering if there's a possiblity to add the option for us to select the OSM Mapnik Grayscale over the Stamen TonerLite theme.

For me there's 2-3 major roads missing. 

Attached are 4 pictures of where two roads are shown on the OSM overlay and not the Stamen overlay

**Comment by ryanteck** [comment]
![screenshot from 2018-12-30 19-39-23](https://user-images.githubusercontent.com/1104745/50550556-c1dc0780-0c6a-11e9-919b-3f83b2312db4.png)
![Uploading Screenshot from 2018-12-30 19-39-17.png…]()
![Uploading Screenshot from 2018-12-30 19-38-56.png…]()
![Uploading Screenshot from 2018-12-30 19-38-30.png…]()

**Comment by ryanteck** [comment]
![screenshot from 2018-12-30 19-39-23](https://user-images.githubusercontent.com/1104745/50550564-d15b5080-0c6a-11e9-90be-601fb6864375.png)

![screenshot from 2018-12-30 19-39-17](https://user-images.githubusercontent.com/1104745/50550566-d1f3e700-0c6a-11e9-9690-f770f0cc10fb.png)
![screenshot from 2018-12-30 19-38-56](https://user-images.githubusercontent.com/1104745/50550565-d1f3e700-0c6a-11e9-986e-42619a70ce25.png)
![screenshot from 2018-12-30 19-38-30](https://user-images.githubusercontent.com/1104745/50550567-d1f3e700-0c6a-11e9-9204-497e7b71dfdb.png)

**Comment by ryanteck** [comment]
Should be a case of modifying lines https://github.com/ttnmapper/ttnmapper-android-v3/blob/8773b8c4eefc0da4f70552794c809509a6e23779/app/src/main/java/org/ttnmapper/phonesurveyor/ui/MapFragment.kt#L82 to line 85 to https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png (a-c array)

With an option or such to select between them?

**Comment by jpmeijers** [comment]
The option to choose different background map themes were added in Build 17 (2019.03.17).

**Comment by ryanteck** [comment]
Just updated, had a look and works great! Doubly so about the fact it has a night mode.
