### ISSUE TITLE
Guide on how to develop for TTN Mapper?

### ISSUE THREAD

**Issue by ryanteck** [ttnmapper/ttnmapper-android-v3#5]
I was wondering if it'd be possible to get a bit added to the readme to just advise what IDE to use and what is needed to get going.

I'm getting an issue about crashlytics not being found.

**Comment by jpmeijers** [comment]
1. There is only one IDE out there that everyone uses for Android Development, so it should not be necessary to specify this.

2. Crashlytics: this is on purpose. The previous version had also had Crashlyics include with all the API keys added into the repo. People would then copy the project (not fork and keep open source), customise it for their use, introduce crashes, and I would still be getting crash reports for them. 
So I decided to not commit the keys. In this way you can either comment out the Crashlytics initialisation lines, or add your own Crashlytics keys. Removing the Crashlytics initialisation and keys from this repo will make us forget to add it back for production builds. So I think the current workaround is the best.

**Comment by ryanteck** [comment]
Just wanted to check that it was Android Studio as I was having a couple of issues with it. Guess my installation is just corrupted instead.

Ok re Point 2.
