### ISSUE TITLE
Timeouts?

### ISSUE THREAD

**Issue by darkman7hr** [ttnmapper/ttnmapper-android-v3#6]
My mapper stops. I tried it on my friends phone also. We are trying to map city but it works some time and then it stops. Any chance you could add "keep-alive" function to settings?

**Comment by jpmeijers** [comment]
This was an issue caused by an unhandled positive "error" from the MQTT library. Thanks to @pstorch and #10 this should be fixed now.

**Comment by darkman7hr** [comment]
Great. Tnx ;)
