### ISSUE TITLE
Old GPS locations result in wrong coverage

### ISSUE THREAD

**Issue by bluepup** [ttnmapper/ttnmapper-android-v3#8]
Sometimes I get coverage in the wrong location. The app marks the wrong spot as location, but the location marked is the last location where the mapping was stopped the last day or so.
Steps to reproduce (not sure if it always works):
 * Do a mapping run and stop the app in an area where there is absolutely no coverage.
 * Don't close the app, but let it be in the background.
 * Go to a place with good coverage and start the app using the symbol as you would when the app would not be in the background.

Sometimes when I do that I get the warning that my GPS location is too old, intermitting with message "finding fix" or others. It seems that there are two or more GPS "processes running in the background if you start the app "again".

**Comment by jpmeijers** [comment]
There is a if-condition in the code that should check if the latest gps location is not too old. Along with this there is also one that should check if the fix accuracy is high enough. These two checks were disabled during development making testing of the app indoors easier. They were never enabled again for the production build.

In the latest release these two checks were enabled again, so this issue should be fixed now.
